# Generated by Django 4.1.3 on 2022-11-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="chatUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=122)),
                ("password", models.CharField(max_length=12)),
                ("name", models.CharField(max_length=122, null=True)),
            ],
        ),
    ]
