# Generated by Django 4.1.3 on 2022-11-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_alter_chatusers_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatusers",
            name="id",
        ),
        migrations.AddField(
            model_name="chatusers",
            name="user_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
