# Generated by Django 4.1.3 on 2022-11-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_remove_chatusers_id_chatusers_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatusers",
            name="user_id",
        ),
        migrations.AddField(
            model_name="chatusers",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
