# Generated by Django 4.0 on 2022-12-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_chatusers_user_id_chatusers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatusers',
            name='privKey',
            field=models.CharField(max_length=1025, null=True),
        ),
        migrations.AddField(
            model_name='chatusers',
            name='pubKey',
            field=models.CharField(max_length=1025, null=True),
        ),
    ]
