# Generated by Django 4.0 on 2022-12-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chats_encryptedtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='Text',
        ),
        migrations.AlterField(
            model_name='chats',
            name='EncryptedText',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
