# Generated by Django 4.0 on 2022-12-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_chats_text_alter_chats_encryptedtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='Audio',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
